version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./images:/usr/share/nginx/html/images
      - ./portFolioStyle.css:/usr/share/nginx/html/portFolioStyle.css
